### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by idkjs** [Nelsonochoam/distributed_pubsub#1]
Thanks for sharing this.

How would you run this to experience this setup?

I get the following error:
```bash
distributed_pubsub/one on  main [!] via 💧 v1.11.2
 [I] ➜ mix phx.server

Compiling 4 files (.ex)
Generated one app
** (Mix) The task "phx.server" could not be found
```

Admittedly, I am not an elixir pro. Thanks, in advance, for any guidance.

**Comment by Nelsonochoam** [comment]
Hey @idkjs I did this more so  I could building a distributed pubsub using just the pubsub module from phoenix, without using the full phoenix framework. In order to test this, you first need to install the dependencies, run `make deps` on the root.

To test it, open 2 terminal windows, in one of them go into the `one` folder (which is meant to represent an app you can run individually), and then on the other window go to the `two` folder. Once you do that, on the window with the `one` folder run `iex --sname node1 -S mix` on the other window run `iex --sname node2 -S mix`. That will start 2 interactive sessions with app `one` running on `node1` and app `two` running on `node2`.

The next step is connecting the nodes. One node1 run `Node.self`  and you will get the node name (it should look something like this :"node1@Nelsons-MacBook-Pro"), copy the name, and go to the window on node2 and run `Node.connect(:"node1@Nelsons-MacBook-Pro"). Once you do that both nodes should be connected in a cluster. (to test that it works, run `Node.list` from any window).

All that is left is starting the consumer on one of the windows, on node2 run `{_, pid} = GenServer.start_link(PubSubDemo.TwoConsumer, [])` (this will start a consumer on app `two`). Finally, go back to node1 and run `PubSubDemo.OnePublisher.publish("hello")` and you will see the message on the window of node2

Hope that helps :)

**Comment by idkjs** [comment]
Mr. Wolf,

Thank you, sir, for these detailed instructions. Just reading this has upped my knowledge level significantly. I am sure it will help and I will try to figure it out if it doesnt before bugging you again. Peace to you. Thank you for taking the time to teach.

**Comment by idkjs** [comment]
Excellent instructions. That works. Thank you. I will play with it now!

```iex
iex(node2@mandalarian)6> Node.connect(:"node1@mandalarian")
true
iex(node2@mandalarian)7> {_, pid} = GenServer.start_link(PubSubDemo.TwoConsumer, [])
{:ok, #PID<0.351.0>}
Message received hello
Message received hello
iex(node2@mandalarian)8>
```
